### ISSUE TITLE
Upgrade composer to Laravel 5.5

### ISSUE THREAD

**Issue by konstantinkonstantinovbgo** [mrabbani/laravel_module_manager#4]
Please update _composer_ to **Laravel** >= **5.3** since it's working fine also under **5.5.4**.

**Comment by mrabbani** [comment]
@konstantinkonstantinovbgo Thank you very much. Updated  to *Laravel 5.5* .

**Comment by konstantinkonstantinovbgo** [comment]
Cool :)
