### ISSUE TITLE
How make seed and db:seed in module ?

### ISSUE THREAD

**Issue by BehroozBvk** [mrabbani/laravel_module_manager#7]
Hello . How to make seed and migrate db:seed in module ? i'am not found command

**Comment by mrabbani** [comment]
`seed` command isn't included yet

**Comment by BehroozBvk** [comment]
How to add?

**Comment by BehroozBvk** [comment]
Thank you, if it was added sooner, that's great

**Comment by mrabbani** [comment]
I have added `module:make:seeder` & `module:db:seed` commands. You may try.

**Comment by BehroozBvk** [comment]
tank. good luck

**Comment by BehroozBvk** [comment]
Apparently undefined

**Comment by mrabbani** [comment]
Make sure you have installed version `1.5.6`. Then try: 
    
    php artisan module:make:seeder module-name SeederClass
